name: notarise and test build addon

on:
  push:
    branches: [main]

jobs:
  notarize-docker-image:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      # Pull an image to notarize; This is where you'd build your local image instead using your preferred method
      - name: debug
        run: docker pull codenotary/cas:bom-docker
        shell: bash


      - name: Notarize Docker image
        #--> Run the GitHub action
        # uses: codenotary/cas-notarize-docker-image-github-action@v1.0.0
        uses: codenotary/cas-notarize-docker-image-bom-github-action@main
        with:
          # make it notarize it's own Docker image B-)
          asset: docker://codenotary/cas:bom-docker
          cas_api_key: ${{ secrets.CAS_API_KEY }}
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --aarch64 \
            --target frpc \
            --docker-hub nra4ever/frpc-ha

name: "Publish"

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: nra4ever
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target frpc \
            --docker-hub nra4ever/frpc-ha